name: Triggered Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name input'
        required: true
        default: 'Mona the Octocat'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print name input
        run: echo "Hello, ${{ github.event.inputs.name }}"
