name: Webhook-Triggered Playercount Update

on:
  repository_dispatch:
    types: [update-csv] # looks for job named "update-csv"
  workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest # ubuntu linux as free, fast, etc.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python # sets up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run CSV update script # runs script to update csv
        run: python playercount/playercount.py

      - name: Commit and push changes # who it was changed by, etc.
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/playercount.csv
          git commit -m "Auto-update CSV $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
          git push
